using UnityEngine;
using TMPro;

public class FinalTimeDisplay : MonoBehaviour
{
    public TextMeshProUGUI finalTimeText;

    private void Start()
    {
        // Initialize the final time text
        if (Timer.Instance != null)
        {
            float finalTime = Timer.Instance.GetElapsedTime();
            DisplayFinalTime(finalTime);
        }
    }

    // The formatting in this function was generated by AI
    // To ensure the final time is displayed in MM:SS:MS format.
    private void DisplayFinalTime(float time)
    {
        // Formats the timer
        int minutes = Mathf.FloorToInt(time / 60);
        int seconds = Mathf.FloorToInt(time % 60);
        int milliseconds = Mathf.FloorToInt((time * 100) % 100);

        finalTimeText.text = "Final Time: " + string.Format("{0:00}:{1:00}:{2:00}", minutes, seconds, milliseconds);
    }
}
